### ISSUE TITLE
Default color still displays for a few seconds

### ISSUE THREAD

**Issue by viperperidot** [PRATAP-KUMAR/focalgdm3#10]
I successfully ran the script and got this to work but I noticed that upon entering your password and logging in, the background changes from the customized selection back to the default Ubuntu purple background for a few seconds before the Gnome desktop loads.

**Comment by PRATAP-KUMAR** [comment]
Thats a different config.. Try this extension

**Comment by viperperidot** [comment]
Thanks looks like that fixed it!
