### ISSUE TITLE
gnome-fallback session

### ISSUE THREAD

**Issue by dmck2** [PRATAP-KUMAR/focalgdm3#11]
It might be worth noting in your docs that your script does not work if one is using gnome-fallback,
lightdm and the unity-greeter.
In this case see  https://wiki.kubuntu.org/LightDM in the section about 'Changing the Wallpaper'.

**Comment by PRATAP-KUMAR** [comment]
Hi read-me file clearly mentions that the script assumes the installation of Ubuntu 20.04 is a fresh installation. in this case, A fresh installation comes with gdm3 as login manager.

**Comment by dmck2** [comment]
Very true. However, since your script comes up first in a search for 'How to change login
background in Ubuntu 20.04', I thought expanding on this might be useful to
readers.

Best, David
