### ISSUE TITLE
Problems with dual-monitor

### ISSUE THREAD

**Issue by TuliodeCastro** [PRATAP-KUMAR/focalgdm3#12]
Having problems with image being stretched when using two monitors. Does it have any solution?

**Comment by PRATAP-KUMAR** [comment]
https://github.com/PRATAP-KUMAR/focalgdm3/issues/2 can you go through this?

**Comment by TuliodeCastro** [comment]
This is how it was supposed to be: 
![one-monitor](https://user-images.githubusercontent.com/64994216/102641015-2a636e00-413a-11eb-926b-48166a302279.jpg)
Working fine using one monitor

The problem starts when I plug another monitor:
![dual-monitor-1st](https://user-images.githubusercontent.com/64994216/102641360-bc6b7680-413a-11eb-8189-ae114f13c2f0.jpg)
![dual-monitor-2nd](https://user-images.githubusercontent.com/64994216/102641603-1704d280-413b-11eb-941d-2c28031001c8.jpg)
The image is stretched between both of them

Is there any way to go around this? 
(Sorry for the image quality, I couldn't find a way to screenshot the login screen)

**Comment by PRATAP-KUMAR** [comment]
Hi.. There seems to be no solution if the number of monitors are changing. You need to change the images according to your monitors setup each time.

**Comment by TuliodeCastro** [comment]
Hmm, I see. Thank you for your feedback anyway!
