### ISSUE TITLE
Dark Green screen error

### ISSUE THREAD

**Issue by Navaneethp360** [PRATAP-KUMAR/focalgdm3#19]
No matter what I do 
I tried setting image
I tried setting color
I tried reset 
I did a reboot
Did another clean install of this 
Still it only shows that dark green color screen ( given in the last screenshots )
Please help

**Comment by PRATAP-KUMAR** [comment]
Hi Dark Green means almost there. Can you provide the commands you used for color and image please?

**Comment by PRATAP-KUMAR** [comment]
Did't you use TrainRun Branch?? Use this branch.
