### ISSUE TITLE
Fill/stretch background image for each screen with multi-monitors

### ISSUE THREAD

**Issue by bryansampson** [PRATAP-KUMAR/focalgdm3#2]
This script works great, except if I select a background image. the image gets spread across all my screens (I have a laptop +2 external screens). The image doesn't fill the each of the screens, it just stretches it part of the way across all screens and then is garbled to fill the rest.

**Comment by PRATAP-KUMAR** [comment]
Hi, thanks for reporting the issue.. I think this kind of Question already raised in AskUbuntu.. if there is a solution found.. Its possible to achieve by tweaking the script too.. Let me go through the AskUbuntu Question I visited  a year ago. Thanks!

**Comment by PRATAP-KUMAR** [comment]
Hi, Please go through this post. I have done it in my multi monitors and worked. Seems that only thing is to create a image that fits the size of all monitors.. https://askubuntu.com/q/1035259/739431

**Comment by PRATAP-KUMAR** [comment]
my monitors setup is 1024x768+1090x1080 So I have created a Image like this
![combined](https://user-images.githubusercontent.com/40719899/80855868-783a6d00-8c62-11ea-9a45-ed7752cb0af6.jpg). Basically the concept I understood is LOGIN Screen is considering All the monitors into one single size and adjusting the Image.

**Comment by bryansampson** [comment]
Thanks for the quick response.  I was able to get it working perfectly!  Thank you again for this awesome script!

**Comment by EliazBobadilla** [comment]
> my monitors setup is 1024x768+1920x1080 So I have created a Image like this
> 
> ![combined](https://user-images.githubusercontent.com/40719899/80855868-783a6d00-8c62-11ea-9a45-ed7752cb0af6.jpg).
> 
> Basically the concept I understood is LOGIN Screen is considering All the monitors into one single size and adjusting the Image.

Could you tell me what program I use to make this edition?pls
I have been trying with: https://jspaint.app/ :(

**Comment by PRATAP-KUMAR** [comment]
Hi.. I did not remember exactly which tool I used.. But I think gThumb or GIMP

**Comment by EliazBobadilla** [comment]
> Hi.. I did not remember exactly which tool I used.. But I think gThumb or GIMP

Thanks
