### ISSUE TITLE
bash syntax error

### ISSUE THREAD

**Issue by olczaq** [PRATAP-KUMAR/focalgdm3#3]
After running the script, I got this error.
![Screenshot from 2020-05-10 20-14-53](https://user-images.githubusercontent.com/18404628/81508240-f1892e00-92fa-11ea-9b00-1bf4df3cdc59.png)

How can I fix it?

**Comment by PRATAP-KUMAR** [comment]
did you edit any contents in the script?

**Comment by PRATAP-KUMAR** [comment]
Hi, I just check the script twice.. It did not give any errors..

**Comment by olczaq** [comment]
I run the original script and I had a erron on line 7, so I just removed
empty lines 1-6, nothing more.

**Comment by PRATAP-KUMAR** [comment]
OK.. can you do like this?
1. open `gedit`
2. copy the content from this link https://github.com/PRATAP-KUMAR/focalgdm3/blob/master/focalgdm3.sh
3. paste in `gedit`
4. save the file as `test.sh`
5. run the command `/bin/bash test.sh --set` with root privileges..

**Comment by olczaq** [comment]
Ok. I'll do it tomorrow and let you know. I have already switched off my
laptop.
Thanks.

**Comment by PRATAP-KUMAR** [comment]
Ok.. please note that there are no empty lines in the script.. see the above pic..
Thank You..

**Comment by olczaq** [comment]
Hello

it works perfectly. When I saved a sh file (Save link as) it occurred to be
completely another source code (you can check the attachment).

Thanks for your help.
Have a nice day.

Aleksandra Tomaszewska

e-mail: tomaszewska.alexandra@gmail.com
Mobile/WhatsApp: +34 648 440 895

**Comment by PRATAP-KUMAR** [comment]
your downloading method might have some issues.. Thank You..
