### ISSUE TITLE
Pop!_Os 20.04 unformated font and icons

### ISSUE THREAD

**Issue by Crylia** [PRATAP-KUMAR/focalgdm3#6]
On Pop!_Os 20.04 the font and icons get too small or too big and everything isnt correctly aligned anymore, i think no CSS is working besides the background.

**Comment by Crylia** [comment]
I might add that when i used the --reset command i had an error and after reboot i couldnt boot anymore. Had to go to recovery options and run the script again to --set a color so i can boot again. Now my login window looks terrible.

**Comment by PRATAP-KUMAR** [comment]
Hi sorry to hear about the problem.. The Script is Strictly for Ubuntu 20.04..

**Comment by PRATAP-KUMAR** [comment]
Hi I have Installed POP OS and made a workaround.. Download this file wget -qO - https://github.com/PRATAP-KUMAR/focalgdm3/archive/TrailRun.tar.gz | tar zx --strip-components=1 focalgdm3-TrailRun/focalgdm3 and replace the 7th line with this content..
`source="/usr/share/gnome-shell/theme/Pop/gnome-shell-theme.gresource"`

**Comment by PRATAP-KUMAR** [comment]
Tested in Pop!_OS 20.04

![Tested](https://user-images.githubusercontent.com/40719899/88480926-6ffa8100-cf76-11ea-8607-b669fa66b41b.png)

**Comment by Crylia** [comment]
Hi, i'm now getting the output
`----------------------------------------
Sorry, Script is only for Ubuntu 20.04
Exiting...
----------------------------------------`

**Comment by Crylia** [comment]
As a workaround i edited the 6th line and removed the check for correct os part

**Comment by PRATAP-KUMAR** [comment]
Hi.. I posted the workaround 13days ago. later, recently I have added that check for OS other than Ubuntu.. so you did the rite way by removing that check for POP OS !!!.. great!
