### ISSUE TITLE
background image not changing

### ISSUE THREAD

**Issue by aptac01** [PRATAP-KUMAR/focalgdm3#7]
Downloaded latest version of that script (git clone https://github.com/PRATAP-KUMAR/focalgdm3.git, commit 23337dcda12ecd4115f6effd254c00b2f21ef2be)

Executed this command:
`sudo ./focalgdm3/focalgdm3 --set`
Chose 1 for image, provided path, got success message and no errors, rebooted my machine. All that resulted in color changed to (and not image set as background) one that looks kinda like #008c75, i have no way of knowing exactly which one.
Сhanging colors works fine though.

Tried this script:
https://github.com/thiggy01/ubuntu-20.04-change-gdm-background
worked fine for me, set image as background as excpected.

screenfetch -n result:
```
 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.4.0-42-generic
 Uptime: 12m
 Packages: 2429
 Shell: bash 5.0.17
 Resolution: 1920x975
 DE: GNOME 3.36.2
 WM: Mutter
 WM Theme: Ambiance
 GTK Theme: Yaru-dark [GTK2/3]
 Icon Theme: ubuntu-mono-dark
 Font: Ubuntu 11
 Disk: 398G / 975G (41%)
 CPU: AMD FX-8350 Eight-Core @ 3x 4,013GHz
 GPU: llvmpipe (LLVM 10.0.0, 128 bits)
 RAM: 1309MiB / 3935MiB
```

maybe its important to note, that machine is running in virtualbox (v. 5.2.34 r133893)

**Comment by PRATAP-KUMAR** [comment]
Hi sorry I missed notification for this..
can you provide the image path?

**Comment by PRATAP-KUMAR** [comment]
Also try this https://github.com/PRATAP-KUMAR/focalgdm3/tree/TrailRun

**Comment by PRATAP-KUMAR** [comment]
The color must be #042320 
![#042320 Color](https://user-images.githubusercontent.com/40719899/90471549-2f88c000-e13c-11ea-9ac0-42e1c3c506a3.png)

**Comment by PRATAP-KUMAR** [comment]
If you have other script to change gdm background.. reset it with that same script.. then try https://github.com/PRATAP-KUMAR/focalgdm3/tree/TrailRun

**Comment by aptac01** [comment]
> 
> 
> Hi sorry I missed notification for this..
> can you provide the image path?

nothing special about it, /home/aptac01/Desktop/bg.jpg, also tried it with /home/aptac01/Desktop/bg.png - with no success.
![wallhaven-268198](https://user-images.githubusercontent.com/67595818/90472932-d2950600-e14b-11ea-80b9-64d90b5f7eb1.jpg)


> 
> 
> Also try this https://github.com/PRATAP-KUMAR/focalgdm3/tree/TrailRun

later today or tomorrow, kinda busy rn



> 
> 
> The color must be #042320

yes, this is it

**Comment by aptac01** [comment]
> 
> 
> Also try this https://github.com/PRATAP-KUMAR/focalgdm3/tree/TrailRun

It didn't help.

Checked out branch TrailRun:

```
aptac01@ubuntu20:~/scripts/ff_login_bg_change$ git remote -v

origin	https://github.com/PRATAP-KUMAR/focalgdm3.git (fetch)

origin	https://github.com/PRATAP-KUMAR/focalgdm3.git (push)

**aptac01@ubuntu20:~/scripts/ff_login_bg_change$ git status**

On branch TrailRun

Your branch is up to date with 'origin/TrailRun'.



nothing to commit, working tree clean

aptac01@ubuntu20:~/scripts/ff_login_bg_change$ sudo ./focalgdm3 /home/aptac01/Desktop/mybg.jpg

[sudo] password for aptac01: 



				     		---------

						|Success|

						---------

				  Changes will be effective after a Reboot

aptac01@ubuntu20:~/scripts/ff_login_bg_change$

```

after reboot it was this color again #042320

**Comment by aptac01** [comment]
and yes, i reverted other script's work beforehand

**Comment by PRATAP-KUMAR** [comment]
Hi.. Ok, I doubt the path you are providing is some how read as different when it is operated in VM.. I never used VM to dig it.. the script is targeted to have the plain color #042320 and the given background path.. the script also has a check that the given path for the bg image is present or not.. Hence I doubt that the path read as different when it is operated in VM.. if you have direct machine or your friends try it in that machine if that works.. definitely we will have to dig on VM side..

**Comment by PRATAP-KUMAR** [comment]
may I know your VM like Oracle Virtual Box, VMWare, Qemu etc.. I will try to reproduce the issue n see...

**Comment by aptac01** [comment]
> may I know your VM like Oracle Virtual Box, VMWare, Qemu etc.. I will try to reproduce the issue n see...

It's clean install of ubuntu in virtualbox (v. 5.2.34 r133893)

**Comment by PRATAP-KUMAR** [comment]
Yes You mentioned it in your first comment.. Ok now I am trying to install but stuck at installation process.. I mean apt install or oracle repository <<-- your install?

**Comment by aptac01** [comment]
I use windows as my host, so i just downloaded exe from their website. I would pick ubuntu repositories

**Comment by PRATAP-KUMAR** [comment]
Oh sorry, I get the point now.. any how I am trying to install VB on Arch Linux.. lets see..

**Comment by PRATAP-KUMAR** [comment]
Hi I installed VB on Arch Linux and then installed Ubuntu 20.04.1 on it. When I ran the script, It worked..

![1](https://user-images.githubusercontent.com/40719899/90662025-80e09e80-e265-11ea-93d6-e9e502518a47.gif)

**Comment by PRATAP-KUMAR** [comment]
![Screenshot from 2020-08-19 21-49-07](https://user-images.githubusercontent.com/40719899/90662348-e0d74500-e265-11ea-871c-345799fd0331.png)

**Comment by aptac01** [comment]
Well, its probably an issue with settings on my machine. I will try to find what might be the cause of that and inform you if i do.
There is a link to other script that worked for me (in my first message) if anyone encounters same behaviour.

**Comment by PRATAP-KUMAR** [comment]
@aptac01 can you go through these comments which I copy pasted from AskUbuntu..

I tried Workaround 2 and specified background image path as /home/username/Pictures/mybackground.jpg but it did not appear on the login screen. On the other hand, when I saved the same image as /usr/share/backgrounds/mybackground.jpg then it was displayed as the background. – rpr Jul 28 at 16:22

Thats the absolute path of your image.. Did you replace username with actual username? Is it a seperate home partition? – UnKNOWn Jul 28 at 16:41    

Yes, /home/username is the path of my home directory. The problem is actually caused by the permissions of that directory: rwxrwx--- (770). The process that displays the login screen background probably runs as gdm user and so it cannot access the picture inside my home directory. – rpr Jul 28 at 18:21

Nice catch..... – UnKNOWn Jul 28 at 18:22

**Comment by aptac01** [comment]
Yeah, that is probably what causing that, i will try that later

**Comment by PRATAP-KUMAR** [comment]
Ok.. I will wait for the result from your side.. hope when you free, you can try that.. thanks for Virtual Box installation.. this is the first time I ever used VB..

**Comment by aptac01** [comment]
It was file permissions issue. 
The reason other script works - it probably copies provided image to some internal directory, and your script sets link of some sort to exact file user provided and gdm uses it.

Case closed! =)

**Comment by PRATAP-KUMAR** [comment]
yes you are rite.. just if you wish try to choose the background from `/usr/share/backgrounds/` and see..
