### ISSUE TITLE
Ubuntu 20.10

### ISSUE THREAD

**Issue by cguasti** [PRATAP-KUMAR/focalgdm3#8]
The script  is not compatible with Ubuntu 20.10

Can be upgraded ?

**Comment by PRATAP-KUMAR** [comment]
Hi, sorry I missed the notification for this...
The script has a check at the start of the script to verify the code name, so you might get the note that Sorry Script is for Ubuntu 20.04 only. Have you tried to edit that from the script?

**Comment by PRATAP-KUMAR** [comment]
I have tested by editing this script `wget -qO - https://github.com/PRATAP-KUMAR/focalgdm3/archive/TrailRun.tar.gz | tar zx --strip-components=1 focalgdm3-TrailRun/focalgdm3` at line number 6 `if [ "$codename" == "focal" ] && [ "$osname" == '"Ubuntu"' ]` to `if [ "$codename" == "groovy" ] && [ "$osname" == '"Ubuntu"' ]` and it worked..

![1](https://user-images.githubusercontent.com/40719899/90714927-71457200-e2c6-11ea-8548-f97f5e87b725.gif)

**Comment by rishabh-prakash** [comment]
> Hi, sorry I missed the notification for this...
> The script has a check at the start of the script to verify the code name, so you might get the note that Sorry Script is for Ubuntu 20.04 only. Have you tried to edit that from the script?

Will it be available for fedora i mean the lockscreen part

**Comment by PRATAP-KUMAR** [comment]
Hi.. I did not get your point.. Can you provide Fedora version so that I will download, install and test it. Are you sure lock screen part not the login? Login is when user is about to login and lock screen is when user already logged in and screen is locked.

**Comment by rishabh-prakash** [comment]
> Hi.. I did not get your point.. Can you provide Fedora version so that I will download, install and test it. Are you sure lock screen part not the login? Login is when user is about to login and lock screen is when user already logged in and screen is locked.

Ye sir I meant the same will this be available on fedora. I am using fedora 32. When ever I try to download it shows this script is only for focal. And I have seen your script it's only for ubuntu focal not for any other distros like fedora 32.

**Comment by PRATAP-KUMAR** [comment]
Ok, thats clear.. I think Fedora server is down.. when I saw your first msg, I started downloading it.. but it is dam slow.. I think almost 6hrs.. only 0.6GB Downloaded out of 1.8GB.. will get back to you Once I work on it..

**Comment by rishabh-prakash** [comment]
> Ok, thats clear.. I think Fedora server is down.. when I saw your first msg, I started downloading it.. but it is dam slow.. I think almost 6hrs.. only 0.6GB Downloaded out of 1.8GB.. will get back to you Once I work on it..

Thankyou sir much appreciated.

**Comment by PRATAP-KUMAR** [comment]
@rishabh-prakash the downloading of ISO took too much time.. I dont know why.. Ok here is the script.. Not have much time to test it in all aspects.. but did upto some extenet.. Please be warned if you know what you are doing.. then proceed.. https://github.com/PRATAP-KUMAR/focalgdm3/tree/fedora32

**Comment by rishabh-prakash** [comment]
> @rishabh-prakash the downloading of ISO took too much time.. I dont know why.. Ok here is the script.. Not have much time to test it in all aspects.. but did upto some extenet.. Please be warned if you know what you are doing.. then proceed.. https://github.com/PRATAP-KUMAR/focalgdm3/tree/fedora32

Thankyou sir for you hardwork.

**Comment by PRATAP-KUMAR** [comment]
Hey, If you decided to try it.. Please let me know the result with a screenhot..

**Comment by PRATAP-KUMAR** [comment]
https://github.com/PRATAP-KUMAR/fedora32-login

**Comment by jeff-knurek** [comment]
why not change the code to 
```
if [ "$codename" == "focal" ] || [ "$codename" == "groovy" ] && [ "$osname" == '"Ubutu"' ]
```
you should update `master` and `TrailRun` branches i guess, as well as the README & repo description
