### ISSUE TITLE
how to change font size?

### ISSUE THREAD

**Issue by RenBaixiao** [PRATAP-KUMAR/focalgdm3#9]
I have just updated my system, and I fount that the font size in login screen and top bar became bigger, looks very ugly.
I found that you know how to change image and color, thus I'd like to know how can I make the font size smaller.

**Comment by PRATAP-KUMAR** [comment]
Hi, have you upgraded from previous versions of Ubuntu to Ubuntu 20.04? I think there is a bug recently on the top bar.

**Comment by RenBaixiao** [comment]
Yes, I installed ubuntu 20.04 directly. Before today's update, it looks normal. After that they became bigger. But in the question on askubuntu.com, his became small. It seems there is not perfect solution yet. I will keep an eye on this. Thanks!

**Comment by PRATAP-KUMAR** [comment]
Hi other link in comments have the issue related to bigger font.. https://askubuntu.com/questions/1268993/ubuntu-20-04-font-and-ui-elements-too-big-on-login. by the way do you have graphics are with the machine?

**Comment by RenBaixiao** [comment]
I have a try. Turn "large text" on then the font size become smaller, and turn "large text" off, the font size become smaller again, which is normal. That is to say, the abnormal big font size is in fact bigger than the "large text".
However this solution can't survive reboot.
My graphics card is RTX 2070, there is also some bugs. For example, my second monitor can't rotate in system settings, I can rotate it in nvidia setting tool, but can' survive reboot, too.

**Comment by PRATAP-KUMAR** [comment]
Ok I think its a critical bug which will be sorted out by GNOME devs soon.
